### ISSUE TITLE
[Bug] URLs Inaccessible via browser

### ISSUE THREAD

**Issue by jhmejia** [TCU-ClassifAI/classifAI#43]
**Describe the bug**
Cannot access URLS like `/about` or `/home` via the browser manually. You have to click each button. This includes when you refresh the page

**To Reproduce**
1. Go to [https://classifai.tcu.edu](https://classifai.tcu.edu)
2. Go to the about page (or just type in https://classifai.tcu.edu/about)
3. Refresh the page

**Expected behavior**
The about page should appear

**Screenshots**
![image](https://github.com/TCU-ClassifAI/classifAI/assets/29128358/dd7b112b-60f9-49fd-8def-a127983b6a90)

**Desktop (please complete the following information):**
 - OS: Any OS 
 - Browser: any browser

**Additional context**

**Comment by J4ninja** [comment]
Copying raw urls into a new tab worked
